name: Coverage

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  determine-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install prerequisite
      run: |
        sudo apt-get update && sudo apt-get install -y python3-dev
        sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev 
        sudo apt-get install -y wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
        sudo curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Create Coverage Report
      run: |
        pip install coverage
        coverage run -m unittest
        coverage lcov
        coverage xml
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml        
        badge: true
        format: 'markdown'
        output: 'both'
    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
    - name: Coveralls Code Coverage Report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
    
      
    

        