name: Coverage

on:
  push:
    branches: [ "main", "stable" ]

permissions:
  contents: read

jobs:
  determine-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v13"
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y python3-dev
        sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev 
        sudo apt-get install -y wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install .[dev]
        pip install -r requirements.txt
    - name: Create Coverage Report
      run: |
        python3 -m pytest --html=report.html --self-contained-html --cov-report xml:coverage.xml --cov-report term --cov-config=.coveragerc --cov="debugging_framework" --cov="debugging_benchmark" --ignore-glob="*test_coverage.py" tests/
        python3 -m coverage lcov
    - uses: actions/upload-artifact@v3
      with:
        name: Test Report
        path: report.html
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov