name: Coverage

on:
  push:
    branches: [ "main", "stable" ]
  pull_request:
    branches: [ "main", "stable" ]

permissions:
  contents: read

jobs:
  determine-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install prerequisite
      run: |
        sudo apt-get update && sudo apt-get install -y python3-dev
        sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev 
        sudo apt-get install -y wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
        sudo curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Create Coverage Report
      run: |
        python3 -m pytest --html=report.html --self-contained-html --cov-report xml:coverage.xml --cov-report term --cov-config=.coveragerc --cov="debugging_framework" --cov="debugging_benchmark" test/
        python3 -m coverage lcov
    - uses: actions/upload-artifact@v3
      with:
        name: Test Report
        path: report.html
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov