name: Test

on:
  push:
    branches: [ "main", "stable", "dev" ]
  pull_request:
    branches: [ "main", "stable", "dev" ]

permissions:
  contents: read

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v13"
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y python3-dev
        sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev 
        sudo apt-get install -y wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install .[dev]
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest